name: business-news-web-scraper
channels:
  - defaults
dependencies:
  - python=3.8
  - pip
  - pip:
    - selenium==4.8.0
    - beautifulsoup4==4.11.1
  - chromedriver-binary==112.0.5615.49
  - beautifulsoup4
  - requests
  - lxml
