name: cs_project1
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.8.20
  - pip=24.2
  - ca-certificates
  - openssl
  - libffi
  - sqlite
  - setuptools
  - wheel
  - scikit-learn=1.3.2
  - scipy=1.10.1
  - numpy=1.24.4
  - networkx
  - jinja2
  - pyyaml
  - pip:
      - huggingface-hub==0.29.1
      - transformers==4.46.3
      - torch==2.4.1
      - sentence-transformers==3.2.1
      - ollama==0.4.7
      - tokenizers==0.20.3
      - tqdm
      - requests
      - urllib3
      - filelock
      - certifi
      - regex