name: cs_project1
channels:
  - defaults
dependencies:
  - python=3.8
  - pip
  - setuptools
  - wheel
  - pytest
  - pip:
      - torch==2.4.1
      - transformers==4.46.3
      - huggingface-hub==0.29.1
      - sentence-transformers==3.2.1
      - scikit-learn==1.3.2
      - numpy==1.24.4
      - tqdm==4.67.1
      - regex
      - requests
      - pyyaml
      - pytest
      - jinja2
      - joblib
      - networkx
      - safetensors
      - typing-extensions
